version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - "63790:6379"
    networks:
      - laravel

  php:
    build:
      context: ./dockerfile
      dockerfile: php
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfile
      dockerfile: composer
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    build:
      context: ./dockerfile
      dockerfile: node
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: ./dockerfile
      dockerfile: artisan
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
